# Generated by Django 4.2.7 on 2025-12-02 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0003_amenity_propertydocument_propertyview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('built_year', models.IntegerField(blank=True, null=True)),
                ('estimated_value_low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimated_value_mid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimated_value_high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comparables_count', models.IntegerField()),
                ('comparables_ids', models.JSONField(default=list)),
                ('market_trend', models.CharField(blank=True, max_length=50)),
                ('trend_strength', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('valuation_date', models.DateField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.city')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='real_estate.property')),
                ('sub_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.subcity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'property valuation',
                'verbose_name_plural': 'property valuations',
                'ordering': ['-valuation_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('property_match', 'Property Match'), ('price_change', 'Price Change'), ('new_listing', 'New Listing'), ('inquiry_response', 'Inquiry Response'), ('system', 'System Notification'), ('promotional', 'Promotional')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('content_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_via', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App')], default='in_app', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='api_notific_user_id_16328d_idx'), models.Index(fields=['created_at'], name='api_notific_created_238c70_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, max_length=20)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('median_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_listings', models.IntegerField()),
                ('new_listings', models.IntegerField()),
                ('sold_listings', models.IntegerField()),
                ('rented_listings', models.IntegerField()),
                ('average_days_on_market', models.IntegerField()),
                ('price_change_qoq', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_change_yoy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inventory_months', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_source', models.CharField(default='UTOPIA', max_length=100)),
                ('is_estimated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.city')),
                ('sub_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.subcity')),
            ],
            options={
                'verbose_name': 'market statistics',
                'verbose_name_plural': 'market statistics',
                'ordering': ['-year', '-quarter', '-month'],
                'unique_together': {('city', 'sub_city', 'property_type', 'year', 'quarter', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action_type'], name='api_auditlo_user_id_f4cf98_idx'), models.Index(fields=['model_name', 'object_id'], name='api_auditlo_model_n_a07f72_idx'), models.Index(fields=['created_at'], name='api_auditlo_created_ec4a64_idx')],
            },
        ),
    ]
