# Generated by Django 4.2.7 on 2025-12-02 19:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_amharic', models.CharField(blank=True, max_length=100)),
                ('amenity_type', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('recreational', 'Recreational'), ('utility', 'Utility'), ('transport', 'Transport'), ('commercial', 'Commercial')], default='general', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
                'ordering': ['amenity_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title_deed', 'Title Deed'), ('construction_permit', 'Construction Permit'), ('occupancy_certificate', 'Occupancy Certificate'), ('floor_plan', 'Floor Plan'), ('site_plan', 'Site Plan'), ('other', 'Other')], max_length=50)),
                ('document', models.FileField(upload_to='property_documents/%Y/%m/%d/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'property document',
                'verbose_name_plural': 'property documents',
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'property view',
                'verbose_name_plural': 'property views',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'inquiry', 'verbose_name_plural': 'inquiries'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order', '-is_primary'], 'verbose_name': 'property image', 'verbose_name_plural': 'property images'},
        ),
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'verbose_name': 'saved search', 'verbose_name_plural': 'saved searches'},
        ),
        migrations.AlterModelOptions(
            name='subcity',
            options={'ordering': ['city', 'name'], 'verbose_name': 'sub city', 'verbose_name_plural': 'sub cities'},
        ),
        migrations.AlterModelOptions(
            name='trackedproperty',
            options={'verbose_name': 'tracked property', 'verbose_name_plural': 'tracked properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_status',
        ),
        migrations.AddField(
            model_name='city',
            name='area_sqkm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('viewing', 'Viewing Request'), ('price', 'Price Inquiry'), ('details', 'More Details')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='response_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='response_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_type',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='has_backup_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_conference_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_construction_permit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_occupancy_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_title_deed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='inquiry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='listed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('for_lease', 'For Lease'), ('auction', 'Auction')], default='for_sale', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold'), ('rented', 'Rented'), ('off_market', 'Off Market')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='property_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='save_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='alert_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('instant', 'Instant')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='match_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcity',
            name='average_price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='subcity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subcity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcity',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcity',
            name='population_density',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subcity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcity',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trackedproperty',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trackedproperty',
            name='price_change_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='contact_preference',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('any', 'Any')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('viewing_scheduled', 'Viewing Scheduled'), ('follow_up', 'Follow Up Required'), ('closed', 'Closed'), ('spam', 'Spam')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_amharic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment/Condo'), ('villa', 'Villa'), ('commercial', 'Commercial'), ('land', 'Land'), ('office', 'Office Space'), ('warehouse', 'Warehouse'), ('farm', 'Farm'), ('hotel', 'Hotel'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='title_amharic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trackedproperty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trackedproperty',
            name='tracking_type',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('landlord', 'Landlord'), ('interested', 'Interested'), ('comparison', 'Comparison'), ('investment', 'Investment')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='subcity',
            unique_together={('city', 'name')},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='real_estate_name_d882f9_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active'], name='real_estate_is_acti_b1a5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='real_estate_propert_92ca33_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_type'], name='real_estate_listing_26c598_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_status'], name='real_estate_propert_be4cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'sub_city'], name='real_estate_city_id_5ae115_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price_etb'], name='real_estate_price_e_3442f5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='real_estate_bedroom_16f3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_featured'], name='real_estate_is_feat_13969e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_verified'], name='real_estate_is_veri_9cdeff_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active'], name='real_estate_is_acti_3c285d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='real_estate_created_b4df12_idx'),
        ),
        migrations.AddField(
            model_name='propertyview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_views', to='real_estate.property'),
        ),
        migrations.AddField(
            model_name='propertyview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='real_estate.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='real_estate.amenity'),
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['property', 'viewed_at'], name='real_estate_propert_d1b2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyview',
            index=models.Index(fields=['user', 'viewed_at'], name='real_estate_user_id_4f59f9_idx'),
        ),
    ]
