# Generated by Django 4.2.7 on 2025-12-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_amenity_propertydocument_propertyview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_id',
        ),
    ]
