# Generated by Django 4.2.7 on 2025-12-02 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_remove_property_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
