# Generated by Django 4.2.7 on 2025-12-03 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0005_property_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('properties', models.ManyToManyField(related_name='comparisons', to='real_estate.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'property comparison',
                'verbose_name_plural': 'property comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('properties', models.ManyToManyField(to='real_estate.property')),
            ],
            options={
                'verbose_name': 'comparison session',
                'verbose_name_plural': 'comparison sessions',
            },
        ),
    ]
