# Generated by Django 4.2.7 on 2025-12-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_alter_property_bathrooms_alter_property_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_video',
            field=models.FileField(blank=True, help_text='Upload property video tour', null=True, upload_to='property_videos/%Y/%m/%d/'),
        ),
    ]
