# Generated by Django 4.2.7 on 2025-12-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_property_property_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='promotion_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='promotion_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='property',
            name='promotion_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='promotion_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('featured', 'Featured'), ('premium', 'Premium'), ('urgent', 'Urgent')], default='basic', max_length=20),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_promoted', 'promotion_end'], name='real_estate_is_prom_7e2dce_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['promotion_tier', 'created_at'], name='real_estate_promoti_557737_idx'),
        ),
    ]
