# Generated by Django 4.2.7 on 2025-12-16 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('real_estate', '0012_alter_property_latitude_alter_property_listing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_listings', models.IntegerField(default=0)),
                ('active_listings', models.IntegerField(default=0)),
                ('new_listings', models.IntegerField(default=0)),
                ('sold_listings', models.IntegerField(default=0)),
                ('rented_listings', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('median_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_views', models.IntegerField(default=0)),
                ('total_inquiries', models.IntegerField(default=0)),
                ('average_days_on_market', models.IntegerField(default=0)),
                ('price_change_daily', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_change_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_change_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inventory_months', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('absorption_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_to_rent_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rental_yield', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Trend',
                'verbose_name_plural': 'Market Trends',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('user_growth_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_properties', models.IntegerField(default=0)),
                ('verified_properties', models.IntegerField(default=0)),
                ('featured_properties', models.IntegerField(default=0)),
                ('promoted_properties', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('avg_session_duration', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_inquiries', models.IntegerField(default=0)),
                ('successful_contacts', models.IntegerField(default=0)),
                ('total_promotions', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('api_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('error_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('server_uptime', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('login_count', models.IntegerField(default=0)),
                ('property_views', models.IntegerField(default=0)),
                ('property_saves', models.IntegerField(default=0)),
                ('searches_performed', models.IntegerField(default=0)),
                ('inquiries_sent', models.IntegerField(default=0)),
                ('total_session_time', models.IntegerField(default=0)),
                ('avg_session_time', models.IntegerField(default=0)),
                ('properties_listed', models.IntegerField(default=0)),
                ('promotions_purchased', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('most_viewed_property_types', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('price_range_preference', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('total_properties', models.IntegerField(default=0)),
                ('properties_for_sale', models.IntegerField(default=0)),
                ('properties_for_rent', models.IntegerField(default=0)),
                ('avg_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_rent_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('price_per_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_views', models.IntegerField(default=0)),
                ('total_inquiries', models.IntegerField(default=0)),
                ('avg_days_on_market', models.IntegerField(default=0)),
                ('properties_sold', models.IntegerField(default=0)),
                ('properties_rented', models.IntegerField(default=0)),
                ('price_trend', models.CharField(choices=[('rising', 'Rising'), ('falling', 'Falling'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('demand_trend', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('key_insights', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='real_estate.city')),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('city', 'period_start', 'period_end', 'period_type')},
            },
        ),
    ]
