# Generated by Django 4.2.7 on 2025-12-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractivity_userprofile_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='agency_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='agent_license_number',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
