# Generated by Django 4.2.7 on 2025-12-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_propertycomparison_comparisonsession'),
        ('users', '0003_rename_agency_name_customuser_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='real_estate.city'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sub_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='real_estate.subcity'),
        ),
    ]
