# Generated by Django 4.2.7 on 2025-12-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('property_view', 'Property Viewed'), ('property_save', 'Property Saved'), ('property_unsave', 'Property Unsaved'), ('search', 'Search Performed'), ('inquiry', 'Inquiry Sent'), ('property_add', 'Property Added'), ('property_edit', 'Property Edited'), ('profile_update', 'Profile Updated'), ('valuation_request', 'Valuation Requested'), ('promotion_purchase', 'Promotion Purchased'), ('promotion_cancel', 'Promotion Cancelled'), ('message_sent', 'Message Sent'), ('message_received', 'Message Received')], max_length=50),
        ),
    ]
