# Generated by Django 4.2.7 on 2026-01-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_useractivity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='currency_preference',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='language_preference',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notification_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='premium_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sms_notifications',
        ),
    ]
