# Generated by Django 4.2.7 on 2026-01-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_is_premium_customuser_premium_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_range_max',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_range_min',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_locations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_property_types',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
