# Generated by Django 4.2.7 on 2026-01-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprofile_budget_range_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency_preference',
            field=models.CharField(choices=[('ETB', 'ETB'), ('USD', 'USD')], default='ETB', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('om', 'Afaan Oromo')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
