# Generated by Django 4.2.7 on 2026-01-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_currency_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='currency_preference',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='language_preference',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='notification_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sms_notifications',
        ),
    ]
