# Generated by Django 4.2.7 on 2026-01-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_currency_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_locations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_property_types',
            field=models.JSONField(default=list),
        ),
    ]
