# Generated by Django 4.2.7 on 2026-01-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_budget_range_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
